[2025-07-24T03:22:56.099+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: TechAndUrbanGrowth.ingestion_population_data manual__2025-07-24T03:22:50.080886+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
