[2025-07-24T03:23:26.882+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: TechAndUrbanGrowth.transform_population_data manual__2025-07-24T03:17:57.368913+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
